app/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
import secrets

db = SQLAlchemy()

class User(UserMixin, db.Model):
    __bind_key__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(), nullable=False)
    password = db.Column(db.String(), nullable=False)
    access_level = db.Column(db.String(), nullable=False)

app/__init__.py
from flask import Flask, current_app
from flask_login import LoginManager
from flask_migrate import Migrate
from .models import db, User
from werkzeug.security import generate_password_hash

login_manager = LoginManager()
migrate = Migrate()

def create_app():
    app = Flask(__name__, template_folder="templates")
    app.config.from_object("config.Config")

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    from .views.login import login_bp
    from .views.home import home_bp
    from .views.contact_us import contact_bp

    app.register_blueprint(login_bp)
    app.register_blueprint(home_bp)
    app.register_blueprint(contact_bp)

    return app

def create_first_user():
    admin_username = current_app.config["ADMIN_LOGIN"]
    admin_password = current_app.config["ADMIN_PASSWORD"]
    admin_access_level = current_app.config["ADMIN_ACCESS"]

    existing_admin = User.query.filter_by(username=admin_username).first()
    if not existing_admin:
        hashed_password = generate_password_hash(admin_password, method="scrypt")
        admin_user = User(
            username=admin_username,
            password=hashed_password,
            access_level=admin_access_level
        )
        db.session.add(admin_user)
        db.session.commit()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/views/contact_us.py
from flask import Blueprint, render_template

from app.decorators import login_required

contact_bp = Blueprint("contact_us", __name__)

def calculate_percentage_score(problem_count, total_count):
    if total_count == 0:
        return "N/A"
    score = (1 - (problem_count / total_count)) * 100
    return f"{round(score, 1)}%"

@contact_bp.route("/contact_us")
@login_required
def contact_us():
    return render_template("contact_us.html")

app/views/home.py
from flask import Blueprint, render_template, request, url_for, jsonify, send_file, current_app
import json
import os
from app.decorators import login_required
import pandas as pd
import requests

home_bp = Blueprint("home", __name__)

@home_bp.route("/home")
@login_required
def home():
    return render_template("home.html")


@home_bp.route("/process_json", methods=["POST"])
@login_required
def process_json():
    try:
        if "file" not in request.files:
            return jsonify({"error": "No file uploaded"}), 400
        file = request.files["file"]
        try:
            data = json.load(file)
        except Exception as e:
            return jsonify({"error": f"Invalid JSON file."}), 400


        payload = {"query_string": data["analyzeResult"]["content"]}
        ai_response = requests.post(
            current_app.config["AZURE_MODEL"],
            json=payload,
            headers={"Content-Type": "application/json"},
            timeout=600
        )

        data_to_share = []
        data_to_save_in_file = []
        for page in ai_response.json()["page_statistics"]:
            problem_texts = []
            for index,error in enumerate(page["problems"]):
                temp_dict = {
                    "Error #": index + 1,
                    "Type": error["error_type"].capitalize(),
                    "Text": error["problem_text"],
                    "Explanation": error["explanation"]
                }
                problem_texts.append(temp_dict)

                data_to_save_in_file.append({
                    "Page number": page["page_number"],
                    "Lexical score %": page['lexical_score'],
                    "Numerical score %": page['numerical_score'],
                    "Error": index + 1,
                    "Type": error["error_type"].capitalize(),
                    "Text": error["problem_text"],
                    "Explanation": error["explanation"]
                })

            data_to_share.append({
                "Page number": page["page_number"],
                "Lexical score %": page['lexical_score'],
                "Numerical score %": page['numerical_score'],
                "Problems": pd.DataFrame(problem_texts).to_html(index=False)
            })

        overall_scores = {
            "lexical_score": str(ai_response.json()['overall_lexical_score']) + "%",
            "numerical_score": str(ai_response.json()['overall_numerical_score']) + "%"
        }

        download_folder = os.path.join(os.getcwd(), "downloads")
        os.makedirs(download_folder, exist_ok=True)

        filename = "analysis.xlsx"
        file_path = os.path.join(download_folder, filename)
        pd.DataFrame.from_dict(data_to_save_in_file).sort_values(["Page number", "Error"]).to_excel(file_path, index=False)

        download_url = url_for("home.download_file", filename=filename)

        return jsonify({
            "structured_data": data_to_share,
            "overall_scores": overall_scores,
            "download_url": download_url
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 400


@home_bp.route("/download/<filename>")
@login_required
def download_file(filename):
    download_folder = os.path.join(os.getcwd(), "downloads")
    return send_file(os.path.join(download_folder, filename), as_attachment=True)

app/views/login.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.models import User
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, current_user
from app.decorators import login_required

login_bp = Blueprint("login", __name__)

@login_bp.route("/")
def index():
    if current_user.is_authenticated:
        return redirect(url_for("home.home"))
    return render_template('login.html')

@login_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for("home.home"))
        flash("Invalid Credentials", "error")
        return render_template("login.html")
    else:
        if current_user.is_authenticated:
            return redirect(url_for("home.home"))
        return render_template("login.html")

@login_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("login.index"))

app/templates/contact_us.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Contact Us</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
</head>
<body>
  <div class="header">
    <span class="welcome">OCR data quality check tool</span>
    <div class="header-right">
      <a href="{{ url_for('home.home') }}">OCR Data Quality Check Tool</a>
      <a href="{{ url_for('login.logout') }}">Logout</a>
    </div>
  </div>
  <div class="container">
    <div class="frame">
        <div class="contact-info">
            <p>Senior Software & AI Engineer</p>
            <p>Emil Shaykhilislamov</p>
            <p>Mobile: +36-70-583-3139</p>
            <p>Hungary, Budapest</p>
        </div>
    </div>
  </div>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>The Tool</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
</head>
<body>
  <div class="header">
    <span class="welcome">OCR data quality check tool</span>
    <div class="header-right">
      <a href="{{ url_for('contact_us.contact_us') }}">Contact</a>
      <a href="{{ url_for('login.logout') }}">Logout</a>
    </div>
  </div>
  <div class="container">
    <div class="frame">
      <p style="color: #5a5a5a;">Select a JSON file using the button below, and your quality check metrics will be neatly displayed in a table.</p>
      <button id="selectFileButton">Select JSON File</button>
      <input type="file" id="jsonInput" accept=".json" style="display: none;">
      <div class="spinner" id="spinner"></div>
      <div id="tableContainer">
        <p>No table data available. Please select a JSON file.</p>
      </div>
      <div id="downloadContainer"></div>
    </div>
  </div>
  <script src="{{ url_for('static', filename='home.js') }}"></script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>OCR Quality Check</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
</head>
<body>

  <div class="container">
    <!-- Left Section -->
    <div class="left">
      <div class="brand"><em style="color: red; font-style: normal">ExxonMobil</em> OCR Competition</div>
      <h1>Welcome to the Next-Generation OCR Data Quality Check Tool <br> Transforming Document Accuracy with Precision & Confidence</h1>
      <p>Leveraging state-of-the-art technology, our tool not only delivers a comprehensive accuracy score but also provides detailed error insights — <em style="color: red; font-style: normal">EM</em>powering you to fine-tune your extraction process for superior results. It even identifies errors in real time.</p>
    </div>

    <!-- Right Section -->
    <div class="right">
      <div class="login-form">
        <h2>Login to your Account</h2>
        <p>Log in now and start your journey to effortless, next-generation document processing.</p>

        <form method="POST" action="/login">
          <label for="username">Email</label>
          <input type="email" name="username" id="username" placeholder="E-mail" required>

          <label for="password">Password</label>
          <input type="password" name="password" id="password" placeholder="Password" required>


          <button type="submit">Login</button>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div style="margin-top: 20px" class="{{ category }}-message error-message">{{ message }}</div>
              {% endfor %}
            {% endif %}
          {% endwith %}
        </form>
      </div>
    </div>
  </div>

</body>
</html>